# Generated by Django 5.0.4 on 2024-04-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='news_category',
            field=models.ManyToManyField(blank=True, to='news.newscategory'),
        ),
    ]
