# Generated by Django 5.0.3 on 2024-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
