# Generated by Django 5.0.3 on 2024-04-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_headline_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=250)),
                ("secondname", models.CharField(max_length=250)),
                ("username", models.CharField(max_length=250)),
                ("password1", models.CharField(max_length=250)),
                ("password2", models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name="headline",
            name="pub_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
