# Generated by Django 5.0.4 on 2024-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_headline_news_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="news_read",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100, null=True)),
                ("articles_read", models.ManyToManyField(to="news.headline")),
            ],
        ),
    ]
