# Generated by Django 5.0.4 on 2024-04-09 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_news_read"),
    ]

    operations = [
        migrations.DeleteModel(
            name="news_read",
        ),
    ]
